In [22]:
import pandas as pd
#df = pd.read_json("Electronics_5.json",lines=True)
df = pd.read_json("Musical_Instruments_5.json",lines=True)
df.head()

,asin,helpful,overall,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,1384719342,"[0, 0]",5,"Not much to write about here, but it does exac...","02 28, 2014",A2IBPI20UZIR0U,"cassandra tu ""Yeah, well, that's just like, u...",good,1393545600
1,1384719342,"[13, 14]",5,The product does exactly as it should and is q...,"03 16, 2013",A14VAT5EAX3D9S,Jake,Jake,1363392000
2,1384719342,"[1, 1]",5,The primary job of this device is to block the...,"08 28, 2013",A195EZSQDW3E21,"Rick Bennette ""Rick Bennette""",It Does The Job Well,1377648000
3,1384719342,"[0, 0]",5,Nice windscreen protects my MXL mic and preven...,"02 14, 2014",A2C00NNG1ZQQG2,"RustyBill ""Sunday Rocker""",GOOD WINDSCREEN FOR THE MONEY,1392336000
4,1384719342,"[0, 0]",5,This pop filter is great. It looks and perform...,"02 21, 2014",A94QU4C90B1AX,SEAN MASLANKA,No more pops when I record my vocals.,1392940800

In [29]:
#reviews preprocess
df = df[['reviewText','overall']]

df =  df[df['overall'] != 3]
X = df['reviewText']
X = X.map(str.lower)
y_dict = {1:0, 2:0, 4:1, 5:1}
y = df['overall'].map(y_dict)

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

count_vect = CountVectorizer(stop_words='english')
X_counts = count_vect.fit_transform(X)
print("Number of features: ",X_counts.shape[0])

#fitting
X_train, X_test, y_train, y_test = train_test_split(X_counts, y, random_state=0)
reg = LogisticRegression()
clf = reg.fit(X_train, y_train)
acc = clf.score(X_test, y_test)
print ('Model Accuracy: ',acc)

Number of features:  9489
Model Accuracy:  0.955752212389

In [49]:
words = count_vect.get_feature_names()
co = clf.coef_.tolist()[0]

words_df = pd.DataFrame({"words":words , "co":co})
words_df = words_df.sort_values(['co', 'words'], ascending=[0, 1])
words_df.head(5)
words_df.tail(5)

             co     words
18164 -1.304197    unless
17268 -1.330338   thought
14292 -1.382159    return
14293 -1.715471  returned
2863  -1.754143     broke